### ISSUE TITLE
Environments are not visible.

### ISSUE THREAD

**Issue by urosjarc** [SC5/lambda-wrapper#11]
```
functions:
  getTrigger:
    handler: src/endpoints/triggers/getTrigger/index.handler
    environment:
      TABLE_NAME: some-table                            <-------- Should be visible process.env.TABLE_NAME
    events:
      - http:
          path: v1/triggers/{id}
          method: get
          cors: true
```

When I run wraper TABLE_NAME is not visible from `process.env.TABLE_NAME`.
